build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with transitive dependencies, indentare is needed
  # checkConfiguration: true

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 40
    thresholdInClasses: 30
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreDeprecated: false
    ignorePrivateFunctions: false
    ignoreOverriddenFunctions: false
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameter: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter:
      - 'Composable'

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*' # Allow PascalCase for Composables
    excludeClassPattern: '.*Test$'

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
    ignorePropertyAnyNumber:
      - 'dp'
      - 'sp'
